// Copyright 2026 The gVisor Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by zip; DO NOT EDIT.

package memmap

import (
	"fmt"

	zap "github.com/zap-proto/go"
)

// ---- FileRange ---------------------------------------------------------

const (
	fileRangeStartAt = 0
	fileRangeEndAt   = 8
	fileRangeSize    = 16
)

var _ interface {
	MarshalZAP() ([]byte, error)
	UnmarshalZAP([]byte) error
} = (*FileRange)(nil)

// MarshalZAP writes FileRange from constant offsets.
func (x *FileRange) MarshalZAP() ([]byte, error) {
	if x == nil {
		return nil, nil
	}
	b := zap.NewBuilder(fileRangeSize + 256)
	ob := b.StartObject(fileRangeSize)
	ob.SetUint64(fileRangeStartAt, uint64(x.Start))
	ob.SetUint64(fileRangeEndAt, uint64(x.End))
	ob.FinishAsRoot()
	return b.Finish(), nil
}

// UnmarshalZAP reads FileRange out of the buffer that arrived.
func (x *FileRange) UnmarshalZAP(data []byte) error {
	if x == nil || len(data) == 0 {
		return nil
	}
	m, err := zap.Parse(data)
	if err != nil {
		return fmt.Errorf("FileRange: %w", err)
	}
	o := m.Root()
	x.Start = uint64(o.Uint64(fileRangeStartAt))
	x.End = uint64(o.Uint64(fileRangeEndAt))
	return nil
}
