// Copyright 2026 The gVisor Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by zip; DO NOT EDIT.

package specutils

import (
	"fmt"
	"strings"

	zap "github.com/zap-proto/go"
)

// ---- GoferMountConf ----------------------------------------------------

const (
	goferMountConfLowerAt = 0
	goferMountConfUpperAt = 1
	goferMountConfSizeAt  = 8
	goferMountConfSize    = 16
)

var _ interface {
	MarshalZAP() ([]byte, error)
	UnmarshalZAP([]byte) error
} = (*GoferMountConf)(nil)

// MarshalZAP writes GoferMountConf from constant offsets.
func (x *GoferMountConf) MarshalZAP() ([]byte, error) {
	if x == nil {
		return nil, nil
	}
	b := zap.NewBuilder(goferMountConfSize + 256)
	ob := b.StartObject(goferMountConfSize)
	ob.SetUint8(goferMountConfLowerAt, uint8(x.Lower))
	ob.SetUint8(goferMountConfUpperAt, uint8(x.Upper))
	ob.SetText(goferMountConfSizeAt, string(x.Size))
	ob.FinishAsRoot()
	return b.Finish(), nil
}

// UnmarshalZAP reads GoferMountConf out of the buffer that arrived.
func (x *GoferMountConf) UnmarshalZAP(data []byte) error {
	if x == nil || len(data) == 0 {
		return nil
	}
	m, err := zap.Parse(data)
	if err != nil {
		return fmt.Errorf("GoferMountConf: %w", err)
	}
	o := m.Root()
	x.Lower = GoferMountConfLowerType(o.Uint8(goferMountConfLowerAt))
	x.Upper = GoferMountConfUpperType(o.Uint8(goferMountConfUpperAt))
	x.Size = string(strings.Clone(o.Text(goferMountConfSizeAt)))
	return nil
}
