// Copyright 2026 The gVisor Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by zip; DO NOT EDIT.

package limits

import (
	"fmt"

	zap "github.com/zap-proto/go"
)

// ---- Limit -------------------------------------------------------------

const (
	limitCurAt = 0
	limitMaxAt = 8
	limitSize  = 16
)

var _ interface {
	MarshalZAP() ([]byte, error)
	UnmarshalZAP([]byte) error
} = (*Limit)(nil)

// MarshalZAP writes Limit from constant offsets.
func (x *Limit) MarshalZAP() ([]byte, error) {
	if x == nil {
		return nil, nil
	}
	b := zap.NewBuilder(limitSize + 256)
	ob := b.StartObject(limitSize)
	ob.SetUint64(limitCurAt, uint64(x.Cur))
	ob.SetUint64(limitMaxAt, uint64(x.Max))
	ob.FinishAsRoot()
	return b.Finish(), nil
}

// UnmarshalZAP reads Limit out of the buffer that arrived.
func (x *Limit) UnmarshalZAP(data []byte) error {
	if x == nil || len(data) == 0 {
		return nil
	}
	m, err := zap.Parse(data)
	if err != nil {
		return fmt.Errorf("Limit: %w", err)
	}
	o := m.Root()
	x.Cur = uint64(o.Uint64(limitCurAt))
	x.Max = uint64(o.Uint64(limitMaxAt))
	return nil
}
