// Copyright 2026 The gVisor Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by zip; DO NOT EDIT.

package kernel

import (
	"fmt"
	"strings"

	zap "github.com/zap-proto/go"
)

// ---- TaskCgroupEntry ---------------------------------------------------

const (
	taskCgroupEntryHierarchyIDAt = 0
	taskCgroupEntryControllersAt = 8
	taskCgroupEntryPathAt        = 16
	taskCgroupEntrySize          = 24
)

var _ interface {
	MarshalZAP() ([]byte, error)
	UnmarshalZAP([]byte) error
} = (*TaskCgroupEntry)(nil)

// MarshalZAP writes TaskCgroupEntry from constant offsets.
func (x *TaskCgroupEntry) MarshalZAP() ([]byte, error) {
	if x == nil {
		return nil, nil
	}
	b := zap.NewBuilder(taskCgroupEntrySize + 256)
	ob := b.StartObject(taskCgroupEntrySize)
	ob.SetUint32(taskCgroupEntryHierarchyIDAt, uint32(x.HierarchyID))
	ob.SetText(taskCgroupEntryControllersAt, string(x.Controllers))
	ob.SetText(taskCgroupEntryPathAt, string(x.Path))
	ob.FinishAsRoot()
	return b.Finish(), nil
}

// UnmarshalZAP reads TaskCgroupEntry out of the buffer that arrived.
func (x *TaskCgroupEntry) UnmarshalZAP(data []byte) error {
	if x == nil || len(data) == 0 {
		return nil
	}
	m, err := zap.Parse(data)
	if err != nil {
		return fmt.Errorf("TaskCgroupEntry: %w", err)
	}
	o := m.Root()
	x.HierarchyID = uint32(o.Uint32(taskCgroupEntryHierarchyIDAt))
	x.Controllers = string(strings.Clone(o.Text(taskCgroupEntryControllersAt)))
	x.Path = string(strings.Clone(o.Text(taskCgroupEntryPathAt)))
	return nil
}
