appname = hanzo-visor
httpport = 19000
runmode = dev
SessionOn = true
copyrequestbody = true
driverName = postgres
dataSourceName = ${DB_DSN||user=hanzo dbname=hanzo_visor host=localhost port=5432 sslmode=disable}
dbName = hanzo_visor
storageBackend = ${STORAGE_BACKEND||base}
dataRoot = ${DATA_ROOT||/data}
tableNamePrefix =
isDemoMode = false
logPostOnly = true
guacamoleEndpoint = 127.0.0.1:4822
iamEndpoint = https://iam.hanzo.ai
clientId = ${IAM_CLIENT_ID||}
clientSecret = ${IAM_CLIENT_SECRET||}
iamOrganization = "hanzo"
iamApplication = "app-hanzo-visor"
commerceUrl = ${COMMERCE_URL||}
commerceToken = ${COMMERCE_TOKEN||}
