// Copyright 2026 The gVisor Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by zip; DO NOT EDIT.

package fd

import (
	"fmt"

	zap "github.com/zap-proto/go"
)

// ---- FD ----------------------------------------------------------------

const (
	fDReadWriterAt = 0
	fDSize         = 8
)

var _ interface {
	MarshalZAP() ([]byte, error)
	UnmarshalZAP([]byte) error
} = (*FD)(nil)

// MarshalZAP writes FD from constant offsets.
func (x *FD) MarshalZAP() ([]byte, error) {
	if x == nil {
		return nil, nil
	}
	b := zap.NewBuilder(fDSize + 256)
	ob := b.StartObject(fDSize)
	{
		eb := zap.NewBuilder(zap.HeaderSize)
		eb.StartObject(0).FinishAsRoot()
		ob.SetBytes(fDReadWriterAt, eb.Finish())
	}
	ob.FinishAsRoot()
	return b.Finish(), nil
}

// UnmarshalZAP reads FD out of the buffer that arrived.
func (x *FD) UnmarshalZAP(data []byte) error {
	if x == nil || len(data) == 0 {
		return nil
	}
	m, err := zap.Parse(data)
	if err != nil {
		return fmt.Errorf("FD: %w", err)
	}
	_ = m
	return nil
}
