// Copyright 2026 The gVisor Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by zip; DO NOT EDIT.

package urpc

import (
	"encoding/binary"
	"fmt"
	"os"

	zap "github.com/zap-proto/go"
)

// ---- FilePayload -------------------------------------------------------

const (
	filePayloadFilesAt = 0
	filePayloadSize    = 8
)

var _ interface {
	MarshalZAP() ([]byte, error)
	UnmarshalZAP([]byte) error
} = (*FilePayload)(nil)

// MarshalZAP writes FilePayload from constant offsets.
func (x *FilePayload) MarshalZAP() ([]byte, error) {
	if x == nil {
		return nil, nil
	}
	b := zap.NewBuilder(filePayloadSize + 256)
	filesAt, filesN := 0, len(x.Files)
	if filesN > 0 {
		var blob []byte
		for range x.Files {
			eb := zap.NewBuilder(zap.HeaderSize)
			eb.StartObject(0).FinishAsRoot()
			enc := eb.Finish()
			var n [4]byte
			binary.LittleEndian.PutUint32(n[:], uint32(len(enc)))
			blob = append(blob, n[:]...)
			blob = append(blob, enc...)
		}
		filesAt = b.WriteBytes(blob)
	}
	ob := b.StartObject(filePayloadSize)
	if filesN > 0 {
		ob.SetList(filePayloadFilesAt, filesAt, filesN)
	}
	ob.FinishAsRoot()
	return b.Finish(), nil
}

// UnmarshalZAP reads FilePayload out of the buffer that arrived.
func (x *FilePayload) UnmarshalZAP(data []byte) error {
	if x == nil || len(data) == 0 {
		return nil
	}
	m, err := zap.Parse(data)
	if err != nil {
		return fmt.Errorf("FilePayload: %w", err)
	}
	o := m.Root()
	if l := o.List(filePayloadFilesAt); l.Len() > 0 {
		rows := make([]*os.File, l.Len())
		for i := range rows {
			rows[i] = new(os.File)
		}
		x.Files = rows
	}
	return nil
}
