// Copyright 2026 The gVisor Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by zip; DO NOT EDIT.

package urpc

import (
	"encoding/binary"
	"fmt"
	"os"
	"strings"

	zap "github.com/zap-proto/go"
)

// ---- Call --------------------------------------------------------------

const (
	callMethodAt = 0
	callArgAt    = 8
	callSize     = 16
)

var _ interface {
	MarshalZAP() ([]byte, error)
	UnmarshalZAP([]byte) error
} = (*Call)(nil)

// MarshalZAP writes Call from constant offsets.
func (x *Call) MarshalZAP() ([]byte, error) {
	if x == nil {
		return nil, nil
	}
	b := zap.NewBuilder(callSize + 256)
	ob := b.StartObject(callSize)
	ob.SetText(callMethodAt, string(x.Method))
	ob.SetBytes(callArgAt, []byte(x.Arg))
	ob.FinishAsRoot()
	return b.Finish(), nil
}

// UnmarshalZAP reads Call out of the buffer that arrived.
func (x *Call) UnmarshalZAP(data []byte) error {
	if x == nil || len(data) == 0 {
		return nil
	}
	m, err := zap.Parse(data)
	if err != nil {
		return fmt.Errorf("Call: %w", err)
	}
	o := m.Root()
	x.Method = string(strings.Clone(o.Text(callMethodAt)))
	x.Arg = []uint8(append([]byte(nil), o.Bytes(callArgAt)...))
	return nil
}

// ---- Echo --------------------------------------------------------------

const (
	echoTextAt        = 0
	echoNumberAt      = 8
	echoFilePayloadAt = 16
	echoSize          = 24
)

var _ interface {
	MarshalZAP() ([]byte, error)
	UnmarshalZAP([]byte) error
} = (*Echo)(nil)

// MarshalZAP writes Echo from constant offsets.
func (x *Echo) MarshalZAP() ([]byte, error) {
	if x == nil {
		return nil, nil
	}
	b := zap.NewBuilder(echoSize + 256)
	ob := b.StartObject(echoSize)
	ob.SetText(echoTextAt, string(x.Text))
	ob.SetInt64(echoNumberAt, int64(x.Number))
	innerFilePayload, err := x.FilePayload.MarshalZAP()
	if err != nil {
		return nil, err
	}
	ob.SetBytes(echoFilePayloadAt, innerFilePayload)
	ob.FinishAsRoot()
	return b.Finish(), nil
}

// UnmarshalZAP reads Echo out of the buffer that arrived.
func (x *Echo) UnmarshalZAP(data []byte) error {
	if x == nil || len(data) == 0 {
		return nil
	}
	m, err := zap.Parse(data)
	if err != nil {
		return fmt.Errorf("Echo: %w", err)
	}
	o := m.Root()
	x.Text = string(strings.Clone(o.Text(echoTextAt)))
	x.Number = int(o.Int64(echoNumberAt))
	if raw := o.Bytes(echoFilePayloadAt); len(raw) > 0 {
		if err := x.FilePayload.UnmarshalZAP(raw); err != nil {
			return err
		}
	}
	return nil
}

// ---- FilePayload -------------------------------------------------------

const (
	filePayloadFilesAt = 0
	filePayloadSize    = 8
)

var _ interface {
	MarshalZAP() ([]byte, error)
	UnmarshalZAP([]byte) error
} = (*FilePayload)(nil)

// MarshalZAP writes FilePayload from constant offsets.
func (x *FilePayload) MarshalZAP() ([]byte, error) {
	if x == nil {
		return nil, nil
	}
	b := zap.NewBuilder(filePayloadSize + 256)
	filesAt, filesN := 0, len(x.Files)
	if filesN > 0 {
		var blob []byte
		for range x.Files {
			eb := zap.NewBuilder(zap.HeaderSize)
			eb.StartObject(0).FinishAsRoot()
			enc := eb.Finish()
			var n [4]byte
			binary.LittleEndian.PutUint32(n[:], uint32(len(enc)))
			blob = append(blob, n[:]...)
			blob = append(blob, enc...)
		}
		filesAt = b.WriteBytes(blob)
	}
	ob := b.StartObject(filePayloadSize)
	if filesN > 0 {
		ob.SetList(filePayloadFilesAt, filesAt, filesN)
	}
	ob.FinishAsRoot()
	return b.Finish(), nil
}

// UnmarshalZAP reads FilePayload out of the buffer that arrived.
func (x *FilePayload) UnmarshalZAP(data []byte) error {
	if x == nil || len(data) == 0 {
		return nil
	}
	m, err := zap.Parse(data)
	if err != nil {
		return fmt.Errorf("FilePayload: %w", err)
	}
	o := m.Root()
	if l := o.List(filePayloadFilesAt); l.Len() > 0 {
		rows := make([]*os.File, l.Len())
		for i := range rows {
			rows[i] = new(os.File)
		}
		x.Files = rows
	}
	return nil
}

// ---- Result ------------------------------------------------------------

const (
	resultSuccessAt = 0
	resultErrAt     = 8
	resultResultAt  = 16
	resultSize      = 24
)

var _ interface {
	MarshalZAP() ([]byte, error)
	UnmarshalZAP([]byte) error
} = (*Result)(nil)

// MarshalZAP writes Result from constant offsets.
func (x *Result) MarshalZAP() ([]byte, error) {
	if x == nil {
		return nil, nil
	}
	b := zap.NewBuilder(resultSize + 256)
	ob := b.StartObject(resultSize)
	ob.SetBool(resultSuccessAt, bool(x.Success))
	ob.SetText(resultErrAt, string(x.Err))
	ob.SetBytes(resultResultAt, []byte(x.Result))
	ob.FinishAsRoot()
	return b.Finish(), nil
}

// UnmarshalZAP reads Result out of the buffer that arrived.
func (x *Result) UnmarshalZAP(data []byte) error {
	if x == nil || len(data) == 0 {
		return nil
	}
	m, err := zap.Parse(data)
	if err != nil {
		return fmt.Errorf("Result: %w", err)
	}
	o := m.Root()
	x.Success = bool(o.Bool(resultSuccessAt))
	x.Err = string(strings.Clone(o.Text(resultErrAt)))
	x.Result = []uint8(append([]byte(nil), o.Bytes(resultResultAt)...))
	return nil
}
