// Copyright 2026 The gVisor Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by zip; DO NOT EDIT.

package stateio

import (
	"fmt"

	zap "github.com/zap-proto/go"
)

// ---- ClientFileRangeSetting --------------------------------------------

const (
	clientFileRangeSettingFileRangeAt = 0
	clientFileRangeSettingPropertyAt  = 8
	clientFileRangeSettingSize        = 16
)

var _ interface {
	MarshalZAP() ([]byte, error)
	UnmarshalZAP([]byte) error
} = (*ClientFileRangeSetting)(nil)

// MarshalZAP writes ClientFileRangeSetting from constant offsets.
func (x *ClientFileRangeSetting) MarshalZAP() ([]byte, error) {
	if x == nil {
		return nil, nil
	}
	b := zap.NewBuilder(clientFileRangeSettingSize + 256)
	ob := b.StartObject(clientFileRangeSettingSize)
	innerFileRange, err := x.FileRange.MarshalZAP()
	if err != nil {
		return nil, err
	}
	ob.SetBytes(clientFileRangeSettingFileRangeAt, innerFileRange)
	ob.SetInt64(clientFileRangeSettingPropertyAt, int64(x.Property))
	ob.FinishAsRoot()
	return b.Finish(), nil
}

// UnmarshalZAP reads ClientFileRangeSetting out of the buffer that arrived.
func (x *ClientFileRangeSetting) UnmarshalZAP(data []byte) error {
	if x == nil || len(data) == 0 {
		return nil
	}
	m, err := zap.Parse(data)
	if err != nil {
		return fmt.Errorf("ClientFileRangeSetting: %w", err)
	}
	o := m.Root()
	if raw := o.Bytes(clientFileRangeSettingFileRangeAt); len(raw) > 0 {
		if err := x.FileRange.UnmarshalZAP(raw); err != nil {
			return err
		}
	}
	x.Property = ClientFileRangeProperty(o.Int64(clientFileRangeSettingPropertyAt))
	return nil
}
