// Copyright 2026 The gVisor Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by zip; DO NOT EDIT.

package checkpoint

import (
	"fmt"
	"strings"

	zap "github.com/zap-proto/go"
)

// ---- ResourceID --------------------------------------------------------

const (
	resourceIDContainerNameAt = 0
	resourceIDPathAt          = 8
	resourceIDSize            = 16
)

var _ interface {
	MarshalZAP() ([]byte, error)
	UnmarshalZAP([]byte) error
} = (*ResourceID)(nil)

// MarshalZAP writes ResourceID from constant offsets.
func (x *ResourceID) MarshalZAP() ([]byte, error) {
	if x == nil {
		return nil, nil
	}
	b := zap.NewBuilder(resourceIDSize + 256)
	ob := b.StartObject(resourceIDSize)
	ob.SetText(resourceIDContainerNameAt, string(x.ContainerName))
	ob.SetText(resourceIDPathAt, string(x.Path))
	ob.FinishAsRoot()
	return b.Finish(), nil
}

// UnmarshalZAP reads ResourceID out of the buffer that arrived.
func (x *ResourceID) UnmarshalZAP(data []byte) error {
	if x == nil || len(data) == 0 {
		return nil
	}
	m, err := zap.Parse(data)
	if err != nil {
		return fmt.Errorf("ResourceID: %w", err)
	}
	o := m.Root()
	x.ContainerName = string(strings.Clone(o.Text(resourceIDContainerNameAt)))
	x.Path = string(strings.Clone(o.Text(resourceIDPathAt)))
	return nil
}
