// Copyright 2026 The gVisor Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by zip; DO NOT EDIT.

package hostarch

import (
	"fmt"

	zap "github.com/zap-proto/go"
)

// ---- AccessType --------------------------------------------------------

const (
	accessTypeReadAt    = 0
	accessTypeWriteAt   = 1
	accessTypeExecuteAt = 2
	accessTypeSize      = 8
)

var _ interface {
	MarshalZAP() ([]byte, error)
	UnmarshalZAP([]byte) error
} = (*AccessType)(nil)

// MarshalZAP writes AccessType from constant offsets.
func (x *AccessType) MarshalZAP() ([]byte, error) {
	if x == nil {
		return nil, nil
	}
	b := zap.NewBuilder(accessTypeSize + 256)
	ob := b.StartObject(accessTypeSize)
	ob.SetBool(accessTypeReadAt, bool(x.Read))
	ob.SetBool(accessTypeWriteAt, bool(x.Write))
	ob.SetBool(accessTypeExecuteAt, bool(x.Execute))
	ob.FinishAsRoot()
	return b.Finish(), nil
}

// UnmarshalZAP reads AccessType out of the buffer that arrived.
func (x *AccessType) UnmarshalZAP(data []byte) error {
	if x == nil || len(data) == 0 {
		return nil
	}
	m, err := zap.Parse(data)
	if err != nil {
		return fmt.Errorf("AccessType: %w", err)
	}
	o := m.Root()
	x.Read = bool(o.Bool(accessTypeReadAt))
	x.Write = bool(o.Bool(accessTypeWriteAt))
	x.Execute = bool(o.Bool(accessTypeExecuteAt))
	return nil
}
