name: Docker
on:
  workflow_dispatch:
  push:
    branches: [main, master, dev, test]
    tags: ['v*']
permissions:
  contents: read
  packages: write
  id-token: write
jobs:
  vm:
    uses: hanzoai/.github/.github/workflows/docker-build.yml@main
    with:
      image: ghcr.io/hanzoai/vm
      target: STANDARD
    secrets: inherit
  vm-allinone:
    uses: hanzoai/.github/.github/workflows/docker-build.yml@main
    with:
      image: ghcr.io/hanzoai/vm-allinone
      target: ALLINONE
    secrets: inherit
